name: Generate Pacman Contribution Graph
permissions:
  contents: write
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman
        uses: rbbit/github-contribution-pacman@main
        with:
          github_user: marcosvallecillos
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pacman
        uses: Minarox/pacman-contribution-graph@v1.0.0
        with:
          username: marcosvallecillos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
